using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lighthouse.API.Migrations
{
    /// <inheritdoc />
    public partial class AddUsersAndRoleLinks : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS staff_members (
                    staff_member_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "FullName" text NOT NULL,
                    "Email" text NOT NULL,
                    "Title" text NOT NULL,
                    "SafehouseId" integer NULL,
                    "CreatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "FK_staff_members_safehouses_SafehouseId"
                        FOREIGN KEY ("SafehouseId")
                        REFERENCES safehouses ("Id")
                        ON DELETE SET NULL
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS users (
                    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    full_name text NOT NULL,
                    email text NOT NULL UNIQUE,
                    password_hash text NOT NULL,
                    role text NOT NULL,
                    is_active boolean NOT NULL DEFAULT true,
                    created_at timestamp with time zone NOT NULL DEFAULT now()
                );
                """);

            migrationBuilder.Sql("ALTER TABLE users ADD COLUMN IF NOT EXISTS resident_id integer NULL;");
            migrationBuilder.Sql("ALTER TABLE users ADD COLUMN IF NOT EXISTS supporter_id integer NULL;");
            migrationBuilder.Sql("ALTER TABLE users ADD COLUMN IF NOT EXISTS staff_member_id integer NULL;");

            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_users_residents_resident_id') THEN
                        ALTER TABLE users
                        ADD CONSTRAINT "FK_users_residents_resident_id"
                        FOREIGN KEY (resident_id) REFERENCES residents ("Id") ON DELETE SET NULL;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_users_supporters_supporter_id') THEN
                        ALTER TABLE users
                        ADD CONSTRAINT "FK_users_supporters_supporter_id"
                        FOREIGN KEY (supporter_id) REFERENCES supporters ("Id") ON DELETE SET NULL;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_users_staff_members_staff_member_id') THEN
                        ALTER TABLE users
                        ADD CONSTRAINT "FK_users_staff_members_staff_member_id"
                        FOREIGN KEY (staff_member_id) REFERENCES staff_members (staff_member_id) ON DELETE SET NULL;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_staff_members_SafehouseId"
                ON staff_members ("SafehouseId");
                """);
            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_resident_id"
                ON users (resident_id) WHERE resident_id IS NOT NULL;
                """);
            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_supporter_id"
                ON users (supporter_id) WHERE supporter_id IS NOT NULL;
                """);
            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_users_staff_member_id"
                ON users (staff_member_id) WHERE staff_member_id IS NOT NULL;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_users_resident_id\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_users_supporter_id\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_users_staff_member_id\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_staff_members_SafehouseId\";");

            migrationBuilder.Sql("ALTER TABLE users DROP CONSTRAINT IF EXISTS \"FK_users_residents_resident_id\";");
            migrationBuilder.Sql("ALTER TABLE users DROP CONSTRAINT IF EXISTS \"FK_users_supporters_supporter_id\";");
            migrationBuilder.Sql("ALTER TABLE users DROP CONSTRAINT IF EXISTS \"FK_users_staff_members_staff_member_id\";");

            migrationBuilder.Sql("ALTER TABLE users DROP COLUMN IF EXISTS resident_id;");
            migrationBuilder.Sql("ALTER TABLE users DROP COLUMN IF EXISTS supporter_id;");
            migrationBuilder.Sql("ALTER TABLE users DROP COLUMN IF EXISTS staff_member_id;");

            migrationBuilder.Sql("DROP TABLE IF EXISTS staff_members;");
        }
    }
}
