using Lighthouse.API.Data;
using Lighthouse.API.Data.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace Lighthouse.API.Infrastructure;

public static class AuthSeeder
{
    public static async Task SeedAsync(IServiceProvider services)
    {
        await using var scope = services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<AppUser>>();

        // Check if the lighthouse tables already exist (pre-populated DB).
        // If so, skip EF migrations and data seeding — the data is already there.
        var canConnect = await db.Database.CanConnectAsync();
        if (!canConnect) return;

        // Check if tables already exist by testing a raw query
        bool tablesExist;
        try
        {
            await db.Database.ExecuteSqlRawAsync(
                "SELECT 1 FROM information_schema.tables WHERE table_name = 'safehouses' LIMIT 1");
            tablesExist = true;
        }
        catch
        {
            tablesExist = false;
        }

        if (tablesExist)
        {
            // Mark all pending migrations as applied so EF doesn't try to CREATE tables
            var pending = (await db.Database.GetPendingMigrationsAsync()).ToList();
            if (pending.Count > 0)
            {
                // Ensure __EFMigrationsHistory exists
                await db.Database.ExecuteSqlRawAsync(
                    """
                    CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                        "MigrationId" character varying(150) NOT NULL,
                        "ProductVersion" character varying(32) NOT NULL,
                        CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
                    )
                    """);
                foreach (var migration in pending)
                {
                    await db.Database.ExecuteSqlRawAsync(
                        $"INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\", \"ProductVersion\") VALUES ('{migration}', '10.0.5') ON CONFLICT DO NOTHING");
                }
            }

            // Ensure the users table has identity-compatible columns.
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE users
                ADD COLUMN IF NOT EXISTS normalized_user_name text,
                ADD COLUMN IF NOT EXISTS normalized_email text,
                ADD COLUMN IF NOT EXISTS first_name text NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS last_name text NOT NULL DEFAULT '',
                ADD COLUMN IF NOT EXISTS security_stamp text,
                ADD COLUMN IF NOT EXISTS concurrency_stamp text,
                ADD COLUMN IF NOT EXISTS phone_number text,
                ADD COLUMN IF NOT EXISTS phone_number_confirmed boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS two_factor_enabled boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS lockout_end timestamp with time zone,
                ADD COLUMN IF NOT EXISTS lockout_enabled boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS access_failed_count integer NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS email_confirmed boolean NOT NULL DEFAULT false
                """);

            // Legacy imported rows can have null/blank stamps, but Identity requires
            // both fields for any UpdateAsync call.
            await db.Database.ExecuteSqlRawAsync(
                """
                UPDATE users
                SET security_stamp = md5(random()::text || clock_timestamp()::text)
                WHERE security_stamp IS NULL OR btrim(security_stamp) = '';

                UPDATE users
                SET concurrency_stamp = md5(random()::text || clock_timestamp()::text)
                WHERE concurrency_stamp IS NULL OR btrim(concurrency_stamp) = '';
                """);

            // Ensure the staff_members table exists
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS staff_members (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "FullName" text NOT NULL,
                    "Email" text NOT NULL,
                    "Title" text NOT NULL DEFAULT 'Social Worker',
                    "SafehouseId" integer,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "PK_staff_members" PRIMARY KEY ("Id")
                )
                """);

            // Ensure core Identity tables exist for external login flow on legacy databases.
            // These tables are normally created by migrations, but this project supports
            // pre-existing operational schemas where migrations are marked as already applied.
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS "AspNetRoles" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" character varying(256),
                    "NormalizedName" character varying(256),
                    "ConcurrencyStamp" text
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
                    ON "AspNetRoles" ("NormalizedName")
                    WHERE "NormalizedName" IS NOT NULL;

                CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" integer NOT NULL,
                    "ClaimType" text,
                    "ClaimValue" text,
                    CONSTRAINT "FK_AspNetUserClaims_users_UserId"
                        FOREIGN KEY ("UserId") REFERENCES users (user_id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId"
                    ON "AspNetUserClaims" ("UserId");

                CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
                    "LoginProvider" character varying(128) NOT NULL,
                    "ProviderKey" character varying(128) NOT NULL,
                    "ProviderDisplayName" text,
                    "UserId" integer NOT NULL,
                    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
                    CONSTRAINT "FK_AspNetUserLogins_users_UserId"
                        FOREIGN KEY ("UserId") REFERENCES users (user_id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId"
                    ON "AspNetUserLogins" ("UserId");

                CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
                    "UserId" integer NOT NULL,
                    "LoginProvider" character varying(128) NOT NULL,
                    "Name" character varying(128) NOT NULL,
                    "Value" text,
                    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
                    CONSTRAINT "FK_AspNetUserTokens_users_UserId"
                        FOREIGN KEY ("UserId") REFERENCES users (user_id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RoleId" integer NOT NULL,
                    "ClaimType" text,
                    "ClaimValue" text,
                    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId"
                        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId"
                    ON "AspNetRoleClaims" ("RoleId");

                CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
                    "UserId" integer NOT NULL,
                    "RoleId" integer NOT NULL,
                    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
                    CONSTRAINT "FK_AspNetUserRoles_users_UserId"
                        FOREIGN KEY ("UserId") REFERENCES users (user_id) ON DELETE CASCADE,
                    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId"
                        FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId"
                    ON "AspNetUserRoles" ("RoleId");
                """);
        }
        else
        {
            // Fresh database — run migrations normally
            await db.Database.MigrateAsync();
        }

        // Seed auth users.
        await EnsureUserAsync(userManager,
            username: "admin", email: "admin@kateri.org",
            password: "Admin#12345Secure", role: UserRoles.Admin);

        await db.SaveChangesAsync();
    }

    private static async Task EnsureUserAsync(
        UserManager<AppUser> userManager,
        string username,
        string email,
        string password,
        string role,
        int? residentId = null,
        int? supporterId = null,
        int? staffMemberId = null)
    {
        var existingByName = await userManager.FindByNameAsync(username);
        if (existingByName is not null)
        {
            return;
        }

        var existingByEmail = await userManager.FindByEmailAsync(email);
        if (existingByEmail is not null)
        {
            return;
        }

        // Legacy fallback: some existing rows may not have normalized identity fields populated yet.
        // Check raw username/email columns directly before attempting to create.
        var normalizedUsername = username.Trim().ToLowerInvariant();
        var normalizedEmail = email.Trim().ToLowerInvariant();
        var existsInLegacyShape = await userManager.Users.AnyAsync(user =>
            (user.UserName != null && user.UserName.ToLower() == normalizedUsername) ||
            (user.Email != null && user.Email.ToLower() == normalizedEmail));
        if (existsInLegacyShape)
        {
            return;
        }

        var user = new AppUser
        {
            FirstName = "Admin",
            LastName = "User",
            Username = username,
            Email = email,
            Role = role,
            IsActive = true,
            CreatedAt = DateTime.UtcNow,
            ResidentId = residentId,
            SupporterId = supporterId,
            StaffMemberId = staffMemberId,
        };
        var result = await userManager.CreateAsync(user, password);
        if (!result.Succeeded)
        {
            throw new InvalidOperationException($"Unable to seed default user: {string.Join("; ", result.Errors.Select(e => e.Description))}");
        }
    }
}
