using Lighthouse.API.Data;
using Lighthouse.API.Data.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace Lighthouse.API.Infrastructure;

public static class AuthSeeder
{
    public static async Task SeedAsync(IServiceProvider services)
    {
        await using var scope = services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<AppUser>>();

        // Check if the lighthouse tables already exist (pre-populated DB).
        // If so, skip EF migrations and data seeding — the data is already there.
        var canConnect = await db.Database.CanConnectAsync();
        if (!canConnect) return;

        // Check if tables already exist by testing a raw query
        bool tablesExist;
        try
        {
            await db.Database.ExecuteSqlRawAsync(
                "SELECT 1 FROM information_schema.tables WHERE table_name = 'safehouses' LIMIT 1");
            tablesExist = true;
        }
        catch
        {
            tablesExist = false;
        }

        if (tablesExist)
        {
            // Mark all pending migrations as applied so EF doesn't try to CREATE tables
            var pending = (await db.Database.GetPendingMigrationsAsync()).ToList();
            if (pending.Count > 0)
            {
                // Ensure __EFMigrationsHistory exists
                await db.Database.ExecuteSqlRawAsync(
                    """
                    CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                        "MigrationId" character varying(150) NOT NULL,
                        "ProductVersion" character varying(32) NOT NULL,
                        CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
                    )
                    """);
                foreach (var migration in pending)
                {
                    await db.Database.ExecuteSqlRawAsync(
                        $"INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\", \"ProductVersion\") VALUES ('{migration}', '10.0.5') ON CONFLICT DO NOTHING");
                }
            }

            // Ensure the users table has identity-compatible columns.
            await db.Database.ExecuteSqlRawAsync(
                """
                ALTER TABLE users
                ADD COLUMN IF NOT EXISTS normalized_user_name text,
                ADD COLUMN IF NOT EXISTS normalized_email text,
                ADD COLUMN IF NOT EXISTS security_stamp text,
                ADD COLUMN IF NOT EXISTS concurrency_stamp text,
                ADD COLUMN IF NOT EXISTS phone_number text,
                ADD COLUMN IF NOT EXISTS phone_number_confirmed boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS two_factor_enabled boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS lockout_end timestamp with time zone,
                ADD COLUMN IF NOT EXISTS lockout_enabled boolean NOT NULL DEFAULT false,
                ADD COLUMN IF NOT EXISTS access_failed_count integer NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS email_confirmed boolean NOT NULL DEFAULT false
                """);

            // Ensure the staff_members table exists
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS staff_members (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "FullName" text NOT NULL,
                    "Email" text NOT NULL,
                    "Title" text NOT NULL DEFAULT 'Social Worker',
                    "SafehouseId" integer,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "PK_staff_members" PRIMARY KEY ("Id")
                )
                """);
        }
        else
        {
            // Fresh database — run migrations normally
            await db.Database.MigrateAsync();
        }

        // Seed auth users.
        await EnsureUserAsync(userManager,
            username: "admin", email: "admin@kateri.org",
            password: "Admin#12345Secure", role: UserRoles.Admin);

        await db.SaveChangesAsync();
    }

    private static async Task EnsureUserAsync(
        UserManager<AppUser> userManager,
        string username,
        string email,
        string password,
        string role,
        int? residentId = null,
        int? supporterId = null,
        int? staffMemberId = null)
    {
        var existingByName = await userManager.FindByNameAsync(username);
        if (existingByName is not null)
        {
            return;
        }

        var existingByEmail = await userManager.FindByEmailAsync(email);
        if (existingByEmail is not null)
        {
            return;
        }

        // Legacy fallback: some existing rows may not have normalized identity fields populated yet.
        // Check raw username/email columns directly before attempting to create.
        var normalizedUsername = username.Trim().ToLowerInvariant();
        var normalizedEmail = email.Trim().ToLowerInvariant();
        var existsInLegacyShape = await userManager.Users.AnyAsync(user =>
            (user.UserName != null && user.UserName.ToLower() == normalizedUsername) ||
            (user.Email != null && user.Email.ToLower() == normalizedEmail));
        if (existsInLegacyShape)
        {
            return;
        }

        var user = new AppUser
        {
            Username = username,
            Email = email,
            Role = role,
            IsActive = true,
            CreatedAt = DateTime.UtcNow,
            ResidentId = residentId,
            SupporterId = supporterId,
            StaffMemberId = staffMemberId,
        };
        var result = await userManager.CreateAsync(user, password);
        if (!result.Succeeded)
        {
            throw new InvalidOperationException($"Unable to seed default user: {string.Join("; ", result.Errors.Select(e => e.Description))}");
        }
    }
}
