using Lighthouse.API.Data;
using Lighthouse.API.Data.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace Lighthouse.API.Infrastructure;

public static class AuthSeeder
{
    public static async Task SeedAsync(IServiceProvider services)
    {
        await using var scope = services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        var passwordHasher = scope.ServiceProvider.GetRequiredService<IPasswordHasher<AppUser>>();

        // Check if the lighthouse tables already exist (pre-populated DB).
        // If so, skip EF migrations and data seeding — the data is already there.
        var canConnect = await db.Database.CanConnectAsync();
        if (!canConnect) return;

        // Check if tables already exist by testing a raw query
        bool tablesExist;
        try
        {
            await db.Database.ExecuteSqlRawAsync(
                "SELECT 1 FROM information_schema.tables WHERE table_name = 'safehouses' LIMIT 1");
            tablesExist = true;
        }
        catch
        {
            tablesExist = false;
        }

        if (tablesExist)
        {
            // Mark all pending migrations as applied so EF doesn't try to CREATE tables
            var pending = (await db.Database.GetPendingMigrationsAsync()).ToList();
            if (pending.Count > 0)
            {
                // Ensure __EFMigrationsHistory exists
                await db.Database.ExecuteSqlRawAsync(
                    """
                    CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                        "MigrationId" character varying(150) NOT NULL,
                        "ProductVersion" character varying(32) NOT NULL,
                        CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
                    )
                    """);
                foreach (var migration in pending)
                {
                    await db.Database.ExecuteSqlRawAsync(
                        $"INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\", \"ProductVersion\") VALUES ('{migration}', '10.0.5') ON CONFLICT DO NOTHING");
                }
            }

            // Ensure the app_users table exists for auth (this table is NOT in lighthouse schema)
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS app_users (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Username" text NOT NULL,
                    "Email" text NOT NULL,
                    "PasswordHash" text NOT NULL,
                    "Role" text NOT NULL DEFAULT 'Staff',
                    "IsActive" boolean NOT NULL DEFAULT true,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    "ResidentId" integer,
                    "SupporterId" integer,
                    "StaffMemberId" integer,
                    CONSTRAINT "PK_app_users" PRIMARY KEY ("Id")
                )
                """);

            // Ensure the staff_members table exists
            await db.Database.ExecuteSqlRawAsync(
                """
                CREATE TABLE IF NOT EXISTS staff_members (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "FullName" text NOT NULL,
                    "Email" text NOT NULL,
                    "Title" text NOT NULL DEFAULT 'Social Worker',
                    "SafehouseId" integer,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT "PK_staff_members" PRIMARY KEY ("Id")
                )
                """);
        }
        else
        {
            // Fresh database — run migrations normally
            await db.Database.MigrateAsync();
        }

        // Seed auth users (uses app_users table, not lighthouse tables)
        await EnsureUserAsync(db, passwordHasher,
            username: "admin", email: "admin@kateri.org",
            password: "Admin#12345", role: UserRoles.Admin);

        await db.SaveChangesAsync();
    }

    private static async Task EnsureUserAsync(
        AppDbContext db,
        IPasswordHasher<AppUser> passwordHasher,
        string username,
        string email,
        string password,
        string role,
        int? residentId = null,
        int? supporterId = null,
        int? staffMemberId = null)
    {
        if (await db.Users.AnyAsync(user => user.Username == username))
        {
            return;
        }

        var user = new AppUser
        {
            Username = username,
            Email = email,
            Role = role,
            IsActive = true,
            CreatedAt = DateTime.UtcNow,
            ResidentId = residentId,
            SupporterId = supporterId,
            StaffMemberId = staffMemberId,
        };
        user.PasswordHash = passwordHasher.HashPassword(user, password);
        db.Users.Add(user);
    }
}
